# Generated by Django 5.2.7 on 2025-11-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_quantity_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Available stock quantity'),
        ),
    ]
